apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: scan-pipeline-image
  
spec:
  params:
  - name: image-scan

  tasks:
  - name: scan-image
    taskRef:
      name: scan-image
    params:
      - name: image-scan
        value: $(params.image-scan)
    


  
  
   
      
